version: '3'

services:
  app:
    image: jftanner/eclancy
    container_name: eclancy
    restart: unless-stopped
    ports:
    - 8082:8082
    environment:
    - NODE_ENV=production
    - PORT=8082
